/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClipborderLandingPageRouteImport } from './routes/clipborder-landing-page'
import { Route as IndexRouteImport } from './routes/index'

const TestimonialGridSectionLazyRouteImport = createFileRoute(
  '/testimonial-grid-section',
)()
const SocialProfileLazyRouteImport = createFileRoute('/social-profile')()
const RecipeLazyRouteImport = createFileRoute('/recipe')()
const ProductPreviewCardLazyRouteImport = createFileRoute(
  '/product-preview-card',
)()
const FourCardFeatureLazyRouteImport = createFileRoute('/four-card-feature')()
const BlogPreviewCardLazyRouteImport = createFileRoute('/blog-preview-card')()

const TestimonialGridSectionLazyRoute =
  TestimonialGridSectionLazyRouteImport.update({
    id: '/testimonial-grid-section',
    path: '/testimonial-grid-section',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/testimonial-grid-section.lazy').then((d) => d.Route),
  )
const SocialProfileLazyRoute = SocialProfileLazyRouteImport.update({
  id: '/social-profile',
  path: '/social-profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/social-profile.lazy').then((d) => d.Route),
)
const RecipeLazyRoute = RecipeLazyRouteImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/recipe.lazy').then((d) => d.Route))
const ProductPreviewCardLazyRoute = ProductPreviewCardLazyRouteImport.update({
  id: '/product-preview-card',
  path: '/product-preview-card',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/product-preview-card.lazy').then((d) => d.Route),
)
const FourCardFeatureLazyRoute = FourCardFeatureLazyRouteImport.update({
  id: '/four-card-feature',
  path: '/four-card-feature',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/four-card-feature.lazy').then((d) => d.Route),
)
const BlogPreviewCardLazyRoute = BlogPreviewCardLazyRouteImport.update({
  id: '/blog-preview-card',
  path: '/blog-preview-card',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/blog-preview-card.lazy').then((d) => d.Route),
)
const ClipborderLandingPageRoute = ClipborderLandingPageRouteImport.update({
  id: '/clipborder-landing-page',
  path: '/clipborder-landing-page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clipborder-landing-page': typeof ClipborderLandingPageRoute
  '/blog-preview-card': typeof BlogPreviewCardLazyRoute
  '/four-card-feature': typeof FourCardFeatureLazyRoute
  '/product-preview-card': typeof ProductPreviewCardLazyRoute
  '/recipe': typeof RecipeLazyRoute
  '/social-profile': typeof SocialProfileLazyRoute
  '/testimonial-grid-section': typeof TestimonialGridSectionLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clipborder-landing-page': typeof ClipborderLandingPageRoute
  '/blog-preview-card': typeof BlogPreviewCardLazyRoute
  '/four-card-feature': typeof FourCardFeatureLazyRoute
  '/product-preview-card': typeof ProductPreviewCardLazyRoute
  '/recipe': typeof RecipeLazyRoute
  '/social-profile': typeof SocialProfileLazyRoute
  '/testimonial-grid-section': typeof TestimonialGridSectionLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clipborder-landing-page': typeof ClipborderLandingPageRoute
  '/blog-preview-card': typeof BlogPreviewCardLazyRoute
  '/four-card-feature': typeof FourCardFeatureLazyRoute
  '/product-preview-card': typeof ProductPreviewCardLazyRoute
  '/recipe': typeof RecipeLazyRoute
  '/social-profile': typeof SocialProfileLazyRoute
  '/testimonial-grid-section': typeof TestimonialGridSectionLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clipborder-landing-page'
    | '/blog-preview-card'
    | '/four-card-feature'
    | '/product-preview-card'
    | '/recipe'
    | '/social-profile'
    | '/testimonial-grid-section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clipborder-landing-page'
    | '/blog-preview-card'
    | '/four-card-feature'
    | '/product-preview-card'
    | '/recipe'
    | '/social-profile'
    | '/testimonial-grid-section'
  id:
    | '__root__'
    | '/'
    | '/clipborder-landing-page'
    | '/blog-preview-card'
    | '/four-card-feature'
    | '/product-preview-card'
    | '/recipe'
    | '/social-profile'
    | '/testimonial-grid-section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClipborderLandingPageRoute: typeof ClipborderLandingPageRoute
  BlogPreviewCardLazyRoute: typeof BlogPreviewCardLazyRoute
  FourCardFeatureLazyRoute: typeof FourCardFeatureLazyRoute
  ProductPreviewCardLazyRoute: typeof ProductPreviewCardLazyRoute
  RecipeLazyRoute: typeof RecipeLazyRoute
  SocialProfileLazyRoute: typeof SocialProfileLazyRoute
  TestimonialGridSectionLazyRoute: typeof TestimonialGridSectionLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonial-grid-section': {
      id: '/testimonial-grid-section'
      path: '/testimonial-grid-section'
      fullPath: '/testimonial-grid-section'
      preLoaderRoute: typeof TestimonialGridSectionLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-profile': {
      id: '/social-profile'
      path: '/social-profile'
      fullPath: '/social-profile'
      preLoaderRoute: typeof SocialProfileLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe': {
      id: '/recipe'
      path: '/recipe'
      fullPath: '/recipe'
      preLoaderRoute: typeof RecipeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-preview-card': {
      id: '/product-preview-card'
      path: '/product-preview-card'
      fullPath: '/product-preview-card'
      preLoaderRoute: typeof ProductPreviewCardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/four-card-feature': {
      id: '/four-card-feature'
      path: '/four-card-feature'
      fullPath: '/four-card-feature'
      preLoaderRoute: typeof FourCardFeatureLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-preview-card': {
      id: '/blog-preview-card'
      path: '/blog-preview-card'
      fullPath: '/blog-preview-card'
      preLoaderRoute: typeof BlogPreviewCardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clipborder-landing-page': {
      id: '/clipborder-landing-page'
      path: '/clipborder-landing-page'
      fullPath: '/clipborder-landing-page'
      preLoaderRoute: typeof ClipborderLandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClipborderLandingPageRoute: ClipborderLandingPageRoute,
  BlogPreviewCardLazyRoute: BlogPreviewCardLazyRoute,
  FourCardFeatureLazyRoute: FourCardFeatureLazyRoute,
  ProductPreviewCardLazyRoute: ProductPreviewCardLazyRoute,
  RecipeLazyRoute: RecipeLazyRoute,
  SocialProfileLazyRoute: SocialProfileLazyRoute,
  TestimonialGridSectionLazyRoute: TestimonialGridSectionLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
