/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Social_profileRouteImport } from './routes/social_profile'
import { Route as Blog_preview_cardRouteImport } from './routes/blog_preview_card'
import { Route as IndexRouteImport } from './routes/index'

const Social_profileRoute = Social_profileRouteImport.update({
  id: '/social_profile',
  path: '/social_profile',
  getParentRoute: () => rootRouteImport,
} as any)
const Blog_preview_cardRoute = Blog_preview_cardRouteImport.update({
  id: '/blog_preview_card',
  path: '/blog_preview_card',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog_preview_card': typeof Blog_preview_cardRoute
  '/social_profile': typeof Social_profileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog_preview_card': typeof Blog_preview_cardRoute
  '/social_profile': typeof Social_profileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog_preview_card': typeof Blog_preview_cardRoute
  '/social_profile': typeof Social_profileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog_preview_card' | '/social_profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog_preview_card' | '/social_profile'
  id: '__root__' | '/' | '/blog_preview_card' | '/social_profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Blog_preview_cardRoute: typeof Blog_preview_cardRoute
  Social_profileRoute: typeof Social_profileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social_profile': {
      id: '/social_profile'
      path: '/social_profile'
      fullPath: '/social_profile'
      preLoaderRoute: typeof Social_profileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_preview_card': {
      id: '/blog_preview_card'
      path: '/blog_preview_card'
      fullPath: '/blog_preview_card'
      preLoaderRoute: typeof Blog_preview_cardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Blog_preview_cardRoute: Blog_preview_cardRoute,
  Social_profileRoute: Social_profileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
